Repository ellmau/adf-obdd, pull requests merged in 2023-05, with the labels that each got.

#63 milestone/frontend
  .dockerignore
  .github/workflows/devskim.yml
  Cargo.lock
  Cargo.toml
  Dockerfile
  README.md
  docs/adf-bdd.md
  docs/adf_bdd.md
  docs/index.md
  flake.lock
  frontend/.editorconfig
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/README.md
  frontend/index.d.ts
  frontend/package.json
  frontend/shell.nix
  frontend/src/app.tsx
  frontend/src/components/adf-details.tsx
  frontend/src/components/adf-new-form.tsx
  frontend/src/components/adf-overview.tsx
  frontend/src/components/app.tsx
  frontend/src/components/footer.tsx
  frontend/src/components/graph-g6.tsx
  frontend/src/components/loading-context.ts
  frontend/src/components/markdown.tsx
  frontend/src/components/snackbar-context.ts
  frontend/src/cpec-logo.png
  frontend/src/help-texts/add-info.md
  frontend/src/help-texts/detail-info.md
  frontend/src/help-texts/example-bdd.png
  frontend/src/iccl-logo.png
  frontend/src/index.html
  frontend/src/innosale-logo.png
  frontend/src/legal.html
  frontend/src/scads-logo.png
  frontend/src/secai-logo.png
  frontend/src/test-data.ts
  frontend/src/tud-logo.png
  frontend/tsconfig.json
  frontend/yarn.lock
  lib/src/adf.rs
  lib/src/datatypes/adf.rs
  lib/src/lib.rs
  lib/src/nogoods.rs
  lib/src/obdd.rs
  server/Cargo.toml
  server/README.md
  server/docker-compose.yml
  server/src/adf.rs
  server/src/config.rs
  server/src/double_labeled_graph.rs
  server/src/main.rs
  server/src/user.rs
Labels: repository, library, server

#146 Update dependencies in yarn.lock
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies, javascript

#148 Update Cargo.lock
  Cargo.lock
  lib/Cargo.toml
  lib/src/adfbiodivine.rs
Labels: dependencies, rust
