Repository ellmau/adf-obdd, pull requests merged in 2023-08, with the labels that each got.

#164 Upgrade dependencies
  Cargo.lock
  flake.lock
  frontend/package.json
  frontend/yarn.lock
  lib/src/nogoods.rs
Labels: enhancement, dependencies

#163 Fix typo in info text
  frontend/src/help-texts/add-info.md
Labels: bug, documentation, javascript

#155 Add flake app and packages for adf-bdd
  Cargo.lock
  bin/Cargo.toml
  flake.lock
  flake.nix
Labels: repository
